### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by carmiker** [tai2/wave_reader_and_writer#1]
First of all, great work @tai2 on this code. It is reliable and works perfectly for what I need.

There is one thing preventing me from publishing code that uses it, however. Since there is no license, it is not usable by any projects with strict licensing requirements:
https://choosealicense.com/no-permission/

For code like this, often a great choice is the MIT license or the Unlicense to make reuse easy for everyone, but it is of course up to the author how the code is licensed.
https://choosealicense.com/licenses/mit/
https://choosealicense.com/licenses/unlicense/

Thanks

**Comment by tai2** [comment]
@carmiker Thanks! I added a `LICENSE` file! 
This code is public domain from now on!

**Comment by carmiker** [comment]
This is great news. Thanks for adding the license to this project.
